theme: jekyll-theme-hacker
title: sec👨‍💻fortress:~$
description: Offensive for Defensive!.
show_downloads: true
show_repo: false

safe: true

plugins:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-seo-tag
  - some-other-jekyll-plugin
  
gems:
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

